version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    depends_on:
      - db
    links:
      - db
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    container_name: react-app
    depends_on:
      - server
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
